language: r
sudo: false
cache: packages

r_github_packages:
 - rqtl/qtl2geno
 - rqtl/qtl2scan
 - rqtl/qtl2convert

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: always
